[config]

[templates.de]
input_path = "./templates/de.css"
output_path = "~/.config/hypr/colors.css"
post_hook = "sh ~/.config/matugen/scripts/reload-de.sh"

[templates.zsh]
input_path = "./templates/zsh-colors.sh"
output_path = "~/.zshcolors"

[templates.hyprland]
input_path = "./templates/hyprland-colors.lua"
output_path = "~/.config/hypr/hyprland/colors.lua"

[templates.neovim]
input_path = "./templates/vim-colors.lua"
output_path = "~/.config/nvim/lua/config/colors.lua"
post_hook = 'pkill -SIGUSR1 nvim'

[templates.kitty]
input_path = "./templates/kitty.conf"
output_path = "~/.config/kitty/themes/Matugen.conf"
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.qt5ct]
input_path = "./templates/qtct-colors.conf"
output_path = "~/.config/qt5ct/colors/matugen.conf"

[templates.qt6ct]
input_path = "./templates/qtct-colors.conf"
output_path = "~/.config/qt6ct/colors/matugen.conf"

[templates.gtk3]
input_path = "./templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/colors.css"
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = "./templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"
post_hook = "sh ~/.config/matugen/scripts/gtk-themes-reload.sh"

[templates.opencode]
input_path = "./templates/opencode.json"
output_path = "~/.config/opencode/themes/matugen.json"

[templates.hyprpaper]
input_path = "./templates/hyprpaper.conf"
output_path = "~/.config/hypr/hyprpaper.conf"
