root = "dotfiles"

[files]
"keyboard-layout.json" = "~/.config/keyboard-layout.json"
".gitconfig" = "~/.gitconfig"
nvim = "~/.config/nvim"
".zshenv" = "~/.zshenv"
".zshrc" = "~/.zshrc"
mise = "~/.config/mise"
".mbg.toml" = "~/.config/.mbg.toml"
"config.ini" = "~/.config/gammastep/config.ini"
wallpapers = "~/Pictures/wallpapers"
".zfunc" = "~/.zfunc"
"config.toml" = "~/.config/jj/config.toml"
kitty = "~/.config/kitty"
hypr = "~/.config/hypr"
