root = "dotfiles"

[files]
".mbg.toml" = "~/.config/.mbg.toml"
"keyboard-layout.json" = "~/.config/keyboard-layout.json"
".zshenv" = "~/.zshenv"
".zshrc" = "~/.zshrc"
"config.ini" = "~/.config/gammastep/config.ini"
"config.toml" = "~/.config/jj/config.toml"
mise = "~/.config/mise"
".zfunc" = "~/.zfunc"
".gitconfig" = "~/.gitconfig"
nvim = "~/.config/nvim"
wallpapers = "~/Pictures/wallpapers"
kitty = "~/.config/kitty"
hypr = "~/.config/hypr"
"custom.conf" = "~/.config/pipewire/pipewire.conf.d/custom.conf"
