hl.on("hyprland.start", function()
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("udiskie &")
    hl.exec_cmd("gammastep &")
    hl.exec_cmd("waybar -c ~/.config/hypr/waybar/config.jsonc -s ~/.config/hypr/waybar/style.css &")
    hl.exec_cmd("swaync -c ~/.config/hypr/swaync/config.json &")
    hl.exec_cmd("hyprpaper -c ~/.config/hypr/hyprpaper.conf &")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("hyprctl setcursor 'Bibata-Modern-Amber' 24")
end)
