"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Pavel Kirilin"
email = "s3riussan@gmail.com"

[templates]
commit_trailers = "if(signature, 'Signed-off-by: ' ++ signature.display(), '')"
draft_commit_description = """
concat(
  builtin_draft_commit_description,
  "\nJJ: ignore-rest\n",
  diff.git(),
)
"""

[remotes.origin]
auto-track-bookmarks = "*"

[git]
sign-on-push = false

[signing]
backend = "gpg"
key = "s3riussan@gmail.com"
behavior = "own"

[ui]
default-command = "log"
conflict-marker-style = "git"
diff-editor = ":builtin"

[ui.graph]
style = "curved"
