-- Generated by Matugen

-- ============================================
-- BASE16 SETUP (must be first - we override below)
-- ============================================
require('base16-colorscheme').setup({
  base00 = '{{colors.background.default.hex}}',
  base01 = '{{colors.surface.default.hex}}',
  base02 = '{{colors.surface_container_low.default.hex}}',
  base03 = '{{colors.surface_container_high.default.hex}}',
  base04 = '{{colors.outline_variant.default.hex}}',
  base05 = '{{colors.on_surface.default.hex}}',
  base06 = '{{colors.outline_variant.default.hex}}',
  base07 = '{{colors.on_surface.default.hex}}',

  base08 = '{{colors.primary_container.default.hex}}',
  base09 = '{{colors.primary_container.default.hex}}',
  base0A = '{{colors.primary_container.default.hex}}',
  base0B = '{{colors.primary_container.default.hex}}',
  base0C = '{{colors.secondary_container.default.hex}}',
  base0D = '{{colors.primary_container.default.hex}}',
  base0E = '{{colors.secondary_container.default.hex}}',
  base0F = '{{colors.tertiary_container.default.hex}}',
})

-- ============================================
-- CUSTOM HIGHLIGHTS (override base16)
-- ============================================
local set = function(groups, opts)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, opts)
  end
end

-- BASE
set({ 'Normal', 'NormalFloat', 'Folded', 'CursorLine', 'CursorLineNr', 'SignColumn', 'TermCursor' }, {
  fg = '{{colors.on_surface.default.hex}}',
  bg = '{{colors.background.default.hex}}',
})

set({ 'LineNr', 'NonText', 'SpecialKey', 'Whitespace' }, {
  fg = '{{colors.outline_variant.default.hex}}',
})

set({ 'Directory', 'Label' }, {
  fg = '{{colors.on_surface.default.hex}}',
  bold = true,
})

-- VARIABLES
set({ 'TSVariable', 'TSVariableBuiltin', 'TSVariableParam', 'Identifier' }, {
  fg = '{{colors.on_surface.default.hex}}',
})

set({ 'TSConstant', 'Constant' }, {
  fg = '{{colors.on_surface.default.hex}}',
})

set({ 'TSNumber', 'TSNumeric', 'Number' }, {
  fg = '{{colors.error_container.default.hex}}',
})

set({ 'TSBoolean', 'Boolean' }, {
  fg = '{{colors.error_container.default.hex}}',
})

set({ 'TSStringEscape', 'StringEscape' }, {
  fg = '{{colors.tertiary_container.default.hex}}',
})

-- FUNCTIONS
set({ 'TSFunction', 'TSFunctionCall', 'Function' }, {
  fg = '{{colors.primary_container.default.hex}}',
  bold = true,
})

set({ 'TSFuncBuiltin', 'BuiltIn' }, {
  fg = '{{colors.primary_container.default.hex}}',
  bold = true,
  underline = true,
})

set({ 'TSFuncMacro' }, {
  fg = '{{colors.secondary_container.default.hex}}',
})

-- METHODS
set({ 'TSMethod', 'TSMethodCall' }, {
  fg = '{{colors.secondary_container.default.hex}}',
})

-- TYPES
set({ 'TSType', 'TSTypeReference', 'Type' }, {
  fg = '{{colors.tertiary_container.default.hex}}',
  italic = true,
})

set({ 'TSTypeClass', 'Structure', 'Typedef' }, {
  fg = '{{colors.tertiary_container.default.hex}}',
  bold = true,
  italic = true,
})

-- KEYWORDS
set({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSKeywordOperator', 'TSRepeat', 'Statement' }, {
  fg = '{{colors.primary_container.default.hex}}',
  bold = true,
  italic = true,
})

set({ 'TSKeywordTypes', 'StorageClass' }, {
  fg = '{{colors.secondary_container.default.hex}}',
  italic = true,
})

-- STRINGS
set({ 'String', 'TSString' }, {
  fg = '{{colors.tertiary_container.default.hex}}',
})

set({ 'TSStringRegex', 'StringRegex' }, {
  fg = '{{colors.error_container.default.hex}}',
})

-- COMMENTS
set({ 'Comment', 'TSComment', 'TSDocumentation' }, {
  fg = '{{colors.outline_variant.default.hex}}',
  italic = true,
})

set({ 'TSCommentStatement' }, {
  fg = '{{colors.outline_variant.default.hex}}',
  bold = true,
  italic = false,
})

-- PUNCTUATION
set({ 'Delimiter', 'TSDelimiter', 'Punctuation' }, {
  fg = '{{colors.outline_variant.default.hex}}',
})

set({ 'PunctuationDelimiter', 'PunctuationBracket' }, {
  fg = '{{colors.outline_variant.default.hex}}',
  bold = true,
})

set({ 'Operator', 'TSOperator' }, {
  fg = '{{colors.primary_container.default.hex}}',
})

-- BRACKETS
set({ 'MatchParen' }, {
  fg = '{{colors.primary_container.default.hex}}',
  bold = true,
  underline = true,
})

set({ 'TSCurlyBracket', 'TSBracket', 'TSParen', 'TSSquareBracket' }, {
  fg = '{{colors.outline_variant.default.hex}}',
})

set({ 'TSParenSpec' }, {
  fg = '{{colors.outline_variant.default.hex}}',
})

set({ 'TSColBracket' }, {
  fg = '{{colors.outline_variant.default.hex}}',
})

-- FIELDS / PARAMETERS / SELF
set({ 'TSField', 'TSProperty' }, {
  fg = '{{colors.on_surface.default.hex}}',
})

set({ 'TSParameter', 'TSParameterReference' }, {
  fg = '{{colors.on_surface.default.hex}}',
  italic = true,
})

set({ 'TSParameterLabel' }, {
  fg = '{{colors.on_surface.default.hex}}',
  bold = true,
})

set({ 'TSSelf', 'TSThis' }, {
  fg = '{{colors.error_container.default.hex}}',
  bold = true,
})

-- INCLUDES
set({ 'TSInclude', 'Include' }, {
  fg = '{{colors.secondary_container.default.hex}}',
  italic = true,
})

-- ERRORS
set({ 'TSError', 'Exception' }, {
  fg = '{{colors.error_container.default.hex}}',
  bold = true,
  underline = true,
})

-- NOTES / WARNINGS
set({ 'TSNote' }, {
  fg = '{{colors.primary_container.default.hex}}',
  bold = true,
})

set({ 'TSWarning' }, {
  fg = '{{colors.tertiary_container.default.hex}}',
  bold = true,
})

set({ 'TSDanger' }, {
  fg = '{{colors.error_container.default.hex}}',
  bold = true,
})

-- SPECIAL / ATTRIBUTES
set({ 'TSSpecial', 'Special', 'SpecialChar', 'Tag' }, {
  fg = '{{colors.tertiary_container.default.hex}}',
})

set({ 'TSAttribute' }, {
  fg = '{{colors.secondary_container.default.hex}}',
})

set({ 'TSAnnotation' }, {
  fg = '{{colors.secondary_container.default.hex}}',
  bold = true,
})

-- TITLES
set({ 'Title' }, {
  fg = '{{colors.primary_container.default.hex}}',
  bold = true,
})

-- CONCEAL
set({ 'Conceal' }, {
  fg = '{{colors.outline_variant.default.hex}}',
})

-- SELECTION
set({ 'Visual', 'VisualNOS' }, {
  bg = '{{colors.surface_container_high.default.hex}}',
  fg = '{{colors.on_surface.default.hex}}',
})

-- SEARCH
set({ 'Search' }, {
  bg = '{{colors.tertiary_container.default.hex}}',
  fg = '{{colors.on_tertiary_container.default.hex}}',
  bold = true,
})

set({ 'CurSearch' }, {
  bg = '{{colors.error_container.default.hex}}',
  fg = '{{colors.on_error_container.default.hex}}',
  bold = true,
})

-- STATUSLINE & TABS
set({ 'StatusLine', 'StatusLineNC', 'TabLine', 'TabLineFill', 'TabLineSel', 'WinBar', 'WinBarNC' }, {
  bg = '{{colors.surface_container_low.default.hex}}',
  fg = '{{colors.on_surface.default.hex}}',
})

set({ 'StatusLineNC', 'TabLineNC', 'WinBarNC' }, {
  fg = '{{colors.outline_variant.default.hex}}',
})

set({ 'TabLineSel' }, {
  bg = '{{colors.surface.default.hex}}',
  fg = '{{colors.on_surface.default.hex}}',
  bold = true,
})

set({ 'TabLine' }, {
  bg = '{{colors.surface_container_low.default.hex}}',
  fg = '{{colors.outline_variant.default.hex}}',
})

-- DIAGNOSTICS
set({ 'DiagnosticError' }, {
  fg = '{{colors.error_container.default.hex}}',
  underline = true,
})

set({ 'DiagnosticWarn' }, {
  fg = '{{colors.tertiary_container.default.hex}}',
  underline = true,
})

set({ 'DiagnosticInfo' }, {
  fg = '{{colors.primary_container.default.hex}}',
  underline = true,
})

set({ 'DiagnosticHint' }, {
  fg = '{{colors.secondary_container.default.hex}}',
  underline = true,
})

set({ 'LspSignatureActiveParameter' }, {
  fg = '{{colors.primary_container.default.hex}}',
  bold = true,
})

set({ 'DiagnosticUnderlineError' }, {
  sp = '{{colors.error_container.default.hex}}',
  undercurl = true,
})

set({ 'DiagnosticUnderlineWarn' }, {
  sp = '{{colors.tertiary_container.default.hex}}',
  undercurl = true,
})

set({ 'DiagnosticUnderlineInfo' }, {
  sp = '{{colors.primary_container.default.hex}}',
  undercurl = true,
})

set({ 'DiagnosticUnderlineHint' }, {
  sp = '{{colors.secondary_container.default.hex}}',
  undercurl = true,
})

set({ 'LspDiagnosticsVirtualTextError' }, {
  fg = '{{colors.error_container.default.hex}}',
  bg = '{{colors.error_container.default.hex}}',
})

set({ 'LspDiagnosticsVirtualTextWarn' }, {
  fg = '{{colors.tertiary_container.default.hex}}',
  bg = '{{colors.tertiary_container.default.hex}}',
})

set({ 'LspDiagnosticsVirtualTextInfo' }, {
  fg = '{{colors.primary_container.default.hex}}',
  bg = '{{colors.primary_container.default.hex}}',
})

set({ 'LspDiagnosticsVirtualTextHint' }, {
  fg = '{{colors.secondary_container.default.hex}}',
  bg = '{{colors.secondary_container.default.hex}}',
})

set({ 'LspDiagnosticsSignError' }, {
  fg = '{{colors.error_container.default.hex}}',
})

set({ 'LspDiagnosticsSignWarn' }, {
  fg = '{{colors.tertiary_container.default.hex}}',
})

set({ 'LspDiagnosticsSignInfo' }, {
  fg = '{{colors.primary_container.default.hex}}',
})

set({ 'LspDiagnosticsSignHint' }, {
  fg = '{{colors.secondary_container.default.hex}}',
})

-- POPUP / AUTOCOMPLETE
set({ 'Pmenu', 'PmenuSbar', 'PmenuThumb' }, {
  bg = '{{colors.surface_container_high.default.hex}}',
  fg = '{{colors.on_surface.default.hex}}',
})

set({ 'PmenuSel' }, {
  bg = '{{colors.primary_container.default.hex}}',
  fg = '{{colors.on_primary_container.default.hex}}',
  bold = true,
})

set({ 'PmenuKind', 'PmenuExtra' }, {
  fg = '{{colors.outline_variant.default.hex}}',
})

-- GIT GUTTER
set({ 'GitSignsAdd', 'GitSignsChange', 'GitSignsDelete' }, {
  fg = '{{colors.primary_container.default.hex}}',
})

set({ 'GitSignsAddNr', 'GitSignsChangeNr', 'GitSignsDeleteNr' }, {
  fg = '{{colors.primary_container.default.hex}}',
})

-- NEO TREE
set({ 'NeoTreeNormal', 'NeoTreeNormalNC' }, {
  bg = '{{colors.surface_container_lowest.default.hex}}',
  fg = '{{colors.on_surface.default.hex}}',
})

set({ 'NeoTreeDimText' }, {
  fg = '{{colors.outline_variant.default.hex}}',
})

-- TELESCOPE
set({ 'TelescopeTitle', 'TelescopePromptTitle', 'TelescopeResultsTitle' }, {
  fg = '{{colors.primary_container.default.hex}}',
  bold = true,
})

set({ 'TelescopeNormal' }, {
  bg = '{{colors.background.default.hex}}',
  fg = '{{colors.on_surface.default.hex}}',
})

-- WHICH-KEY
set({ 'WhichKey' }, {
  fg = '{{colors.primary_container.default.hex}}',
})

set({ 'WhichKeySeperator' }, {
  fg = '{{colors.secondary_container.default.hex}}',
})

set({ 'WhichKeyGroup' }, {
  fg = '{{colors.secondary_container.default.hex}}',
  bold = true,
})

set({ 'WhichKeyDesc' }, {
  fg = '{{colors.tertiary_container.default.hex}}',
})

-- CMP
set({ 'CmpDocumentation', 'CmpDocumentationBorder' }, {
  bg = '{{colors.surface.default.hex}}',
  fg = '{{colors.on_surface.default.hex}}',
})

set({ 'CmpSelected' }, {
  bg = '{{colors.surface_container_high.default.hex}}',
  bold = true,
})

set({ 'CmpBorder' }, {
  fg = '{{colors.outline_variant.default.hex}}',
})

-- DAP
set({ 'DapStopped' }, {
  fg = '{{colors.primary_container.default.hex}}',
  bg = '{{colors.surface_container_low.default.hex}}',
})

set({ 'DapBreakpoint' }, {
  fg = '{{colors.error_container.default.hex}}',
})

set({ 'DapBreakpointRejected' }, {
  fg = '{{colors.error_container.default.hex}}',
  bold = true,
})
